### ISSUE TITLE
StatusChecker.py not working.

### ISSUE THREAD

**Issue by amandesai01** [amandesai01/CloudMimics#3]
Here is error stack trace:
```
Traceback (most recent call last):
  File "statuschecker.py", line 23, in <module>
    check_servers()
  File "statuschecker.py", line 16, in check_servers
    if ping(server['url']):
  File "/opt/anaconda3/lib/python3.7/site-packages/ping3.py", line 81, in wrapper
    func_return = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/ping3.py", line 278, in ping
    with socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP) as sock:
  File "/opt/anaconda3/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by deepanshu2506** [comment]
the error is due to the fact that python does not have permission to access raw packets nad hence your socket does not initialize

run it using sudo or give python the permission to listen to raw packets

`sudo setcap cap_net_raw+ep $(which python)`

This will allow Python to capture raw packets, without having to give it full root permission.

**Comment by amandesai01** [comment]
I see. Thanks for help @deepanshu2506.
